debug: true
spring:
  swagger2:
    group:
      v1:
        base-package: in.hocg.swagger2.spring.boot.samples.simple.api.v1
#        path-mapping: /v1/**
        title: Project API Title
        description: Project API Description
        version: 1.0.1
        terms-of-service-url: https://hocg.in
        extensions:
          k: v
          k2: v2
        license: MIT
        license-url: https://hocg.in/MIT
        contact:
          name: hocgin
          url: https://hocg.in
          email: hocgin@gmail.com
      v2:
        base-package: in.hocg.swagger2.spring.boot.samples.simple.api.v2
#        path-mapping: /v2/**
        title: Project API Title
        description: Project API Description
        version: 1.0.1
        terms-of-service-url: https://hocg.in
        extensions:
          k: v
          k2: v2
        license: MIT
        license-url: https://hocg.in/MIT
        contact:
          name: hocgin
          url: https://hocg.in
          email: hocgin@gmail.com
